# Dispatch — PR ops: mark ready-for-review candidate

PR-op task generated by `scripts/dispatch_pr_ops.sh`. Universal: no
agent-CLI assumptions, no project-name hardcoding. Substitute the
`{{KEY}}` placeholders before sending; do not edit the structure.

## Objectif

Verify the assigned draft pull request meets the readiness criteria
required by the project policy and, if every gate is met, flip it from
draft to ready-for-review. The orchestrator has authorized this task
with mutation scope `{{MUTATION_SCOPE}}` (which includes `pr_state`
because flipping draft/ready is an external PR state change).

- pr-ops-task: mark_ready_candidate
- external-pr-mutations: {{MUTATION_SCOPE}}

## Context

- PR: {{PR_URL}}
- Repo: {{REPO}}
- Branch: `{{BRANCH}}` → base `{{BASE_BRANCH}}`
- Project: `{{PROJECT}}`
- Agent label: `{{AGENT_LABEL}}` (worktree: `{{AGENT_WORKDIR}}`)
- PR body hash: {{PR_BODY_HASH}}
- PR body reference: `{{PR_BODY_REFERENCE}}`
- Linked issue context from PR body: {{LINKED_ISSUE_CONTEXT}}
- mergeable: `{{MERGEABLE}}`
- CI rollup at task start: `{{CI_ROLLUP}}` (must be `pass` for ready-flip)
- Failed check names: {{CI_FAILED_CHECK_NAMES}}
- Failed-check log/run retrieval:
{{CI_FAILED_LOG_COMMANDS}}
- File ownership for this PR: {{FILE_OWNERSHIP}}
- Coordination-surface (hotspot) files in this PR: {{HOTSPOT_FILES}}

## Format de sortie attendu

Either (a) `gh pr ready {{PR_NUMBER}} --repo {{REPO}}` after every
readiness gate is green, plus a short status report enumerating each
gate and its verdict; or (b) a structured blocker recording exactly
which gate refused the flip. Do not merge, do not push commits, do
not edit labels/assignees, do not change the PR title or body.

## Tools / sources autorises

- `cd {{AGENT_WORKDIR}}` (always first)
- Read-only inspection of the PR via `gh pr view {{PR_NUMBER}} --json
  state,mergeable,mergeStateStatus,reviewDecision,statusCheckRollup,isDraft`
- Verification: `{{VERIFICATION_COMMANDS}}` (must pass before flip)
- Audit evidence: `record_local_gate_evidence` from `lib/audit_log.sh`
  before the flip, with one entry per gate (CI, mergeable, review,
  hotspots, deploy gate)
- The flip itself: `gh pr ready {{PR_NUMBER}} --repo {{REPO}}` —
  authorised under scope `pr_state` only

## Readiness gates (every gate must be MET to flip)

- CI rollup status equals `pass` (no failed, pending, or missing checks)
- `mergeable` equals `MERGEABLE` (refuse on `UNKNOWN` or `CONFLICTING`)
- `mergeStateStatus` is one of `CLEAN`, `HAS_HOOKS`, `UNSTABLE`
  (refuse on `BLOCKED`, `DIRTY`, `BEHIND`, `UNKNOWN`)
- No coordination-surface hotspot conflicts open against other agents
- No deploy-gate-external-wait signal on this PR

## Boundaries / interdictions

- Merge policy boundary: {{MERGE_POLICY}} — do NOT merge from this task.
- Out of scope: pushing commits, rebasing, editing PR title/body,
  changing assignees/labels/reviewers, requesting reviews.
- No `--no-verify`, `--admin`, `gh pr merge`, or any mutation scope
  beyond `{{MUTATION_SCOPE}}`.
- Refuse the flip and record a structured blocker if any gate is
  unmet. Agents must NEVER flip ready-for-review on a draft whose CI
  is pending or red.

## Definition of Done verifiable

- [ ] `pwd` post-cd inside `{{AGENT_WORKDIR}}`
- [ ] Every gate above is recorded as MET in the audit evidence
      OR a blocker is filed naming the unmet gate
- [ ] No PR mutation outside `{{MUTATION_SCOPE}}`
- [ ] If flipped: PR shows `isDraft=false` and the resulting
      `mergeStateStatus` is reported

## Preuves attendues

- `pwd` post-cd
- `git config user.name && git config user.email`
- Per-gate verdict line: `<gate-name> → MET|UNMET (<evidence ref>)`
- {{EXPECTED_EVIDENCE}}
- `gh pr view {{PR_NUMBER}} --repo {{REPO}} --json
  isDraft,mergeable,mergeStateStatus,statusCheckRollup` post-action

— PR-ops dispatch generated by `scripts/dispatch_pr_ops.sh`. Mode: `{{MODE}}`. Wave: `{{WAVE_ID}}`.
