# Dispatch — PR ops: fix CI

PR-op task generated by `scripts/dispatch_pr_ops.sh`. Universal: no
agent-CLI assumptions, no project-name hardcoding. Substitute the
`{{KEY}}` placeholders before sending; do not edit the structure.

## Objectif

Bring the failing checks on the assigned pull request back to green
without altering scope. The orchestrator has authorized this task with
mutation scope `{{MUTATION_SCOPE}}` (declared on its own line below).

- pr-ops-task: fix_ci
- external-pr-mutations: {{MUTATION_SCOPE}}

## Context

- PR: {{PR_URL}}
- Repo: {{REPO}}
- Branch: `{{BRANCH}}` → base `{{BASE_BRANCH}}`
- Project: `{{PROJECT}}`
- Agent label: `{{AGENT_LABEL}}` (worktree: `{{AGENT_WORKDIR}}`)
- PR body hash: {{PR_BODY_HASH}}
- PR body reference: `{{PR_BODY_REFERENCE}}`
- Linked issue context from PR body: {{LINKED_ISSUE_CONTEXT}}
- Failing checks: {{CI_FAILING}}
- Failed check names: {{CI_FAILED_CHECK_NAMES}}
- Pending checks: {{CI_PENDING}}
- Failed-check log/run retrieval:
{{CI_FAILED_LOG_COMMANDS}}
- Pending-check log/run retrieval:
{{CI_PENDING_LOG_COMMANDS}}
- File ownership for this PR: {{FILE_OWNERSHIP}}
- Coordination-surface (hotspot) files in this PR: {{HOTSPOT_FILES}}

## Format de sortie attendu

A pushed commit on `{{BRANCH}}` that turns the failing checks green,
plus a short status report mapping every failing check to the change
that addressed it. Do not rebase, do not change PR title or body, do
not flip draft/ready, do not add reviewers/assignees/labels, do not
merge.

## Tools / sources autorises

- `cd {{AGENT_WORKDIR}}` (always first)
- `git fetch origin && git pull --ff-only` only when on `{{BRANCH}}`
- Edit only files listed in "File ownership"; refuse to touch any
  hotspot file outside that list (see `lib/file_hotspots.sh`)
- Verification: `{{VERIFICATION_COMMANDS}}`
- Push: `git push origin {{BRANCH}}` (no `--force`, no `--force-with-lease`)
- Audit evidence: `record_local_gate_evidence` from `lib/audit_log.sh`
  before any reportable change

## Boundaries / interdictions

- Merge policy boundary: {{MERGE_POLICY}} — do NOT merge from this task.
- Out of scope: rebasing onto `{{BASE_BRANCH}}` (covered by `resolve_conflict`),
  any other PR, any other branch, any other project's worktree.
- No `--no-verify`, `--admin`, `git push --force`, branch-protection bypass,
  required-review bypass, or scope expansion beyond File ownership.
- External PR mutations beyond `{{MUTATION_SCOPE}}` are refused; declaring
  more scopes here without orchestrator authorization will trip the
  external-pr-mutation gate (`scripts/dispatch_ticket.sh` exit code
  `ORCH_EXTERNAL_PR_MUTATION_REFUSED_EXIT_CODE`).

## Definition of Done verifiable

- [ ] `pwd` post-cd inside `{{AGENT_WORKDIR}}`
- [ ] `git status --short --branch` clean before any edit
- [ ] Every failing check listed above is green on the new HEAD
- [ ] No file outside "File ownership" is modified
- [ ] No PR mutation outside `{{MUTATION_SCOPE}}`
- [ ] Push succeeded; new HEAD reported in evidence

## Preuves attendues

- `pwd` post-cd
- `git config user.name && git config user.email`
- `git rev-parse HEAD` before and after the fix
- {{EXPECTED_EVIDENCE}}
- For each failing check: a one-line mapping `<check-name> → <commit-sha>`
- `gh pr checks {{PR_NUMBER}} --repo {{REPO}}` post-push (audit evidence)

— PR-ops dispatch generated by `scripts/dispatch_pr_ops.sh`. Mode: `{{MODE}}`. Wave: `{{WAVE_ID}}`.
