# Dispatch — PR ops: resolve conflict / refresh branch

PR-op task generated by `scripts/dispatch_pr_ops.sh`. Universal: no
agent-CLI assumptions, no project-name hardcoding. Substitute the
`{{KEY}}` placeholders before sending; do not edit the structure.

## Objectif

Refresh the assigned branch against `{{BASE_BRANCH}}` and resolve any
content conflicts produced by the rebase. Do not expand scope beyond
the conflict hunks. The orchestrator has authorized this task with
mutation scope `{{MUTATION_SCOPE}}`.

- pr-ops-task: resolve_conflict
- external-pr-mutations: {{MUTATION_SCOPE}}

## Context

- PR: {{PR_URL}}
- Repo: {{REPO}}
- Branch: `{{BRANCH}}` → base `{{BASE_BRANCH}}`
- Project: `{{PROJECT}}`
- Agent label: `{{AGENT_LABEL}}` (worktree: `{{AGENT_WORKDIR}}`)
- PR body hash: {{PR_BODY_HASH}}
- PR body reference: `{{PR_BODY_REFERENCE}}`
- Linked issue context from PR body: {{LINKED_ISSUE_CONTEXT}}
- mergeable: `{{MERGEABLE}}` (must be `CONFLICTING` for this task; refuse if `UNKNOWN`)
- Reported conflict signal(s): {{CONFLICT_SIGNALS}}
- Failed check names: {{CI_FAILED_CHECK_NAMES}}
- Failed-check log/run retrieval:
{{CI_FAILED_LOG_COMMANDS}}
- File ownership for this PR: {{FILE_OWNERSHIP}}
- Coordination-surface (hotspot) files in this PR: {{HOTSPOT_FILES}}

## Format de sortie attendu

A `git push --force-with-lease` on `{{BRANCH}}` after the rebase, plus a
short status report listing every conflicted file with the chosen
resolution rationale. Plain `--force` is forbidden. Do not change PR
title or body, do not flip draft/ready, do not add reviewers, do not
merge.

## Tools / sources autorises

- `cd {{AGENT_WORKDIR}}` (always first)
- `git fetch origin {{BASE_BRANCH}}`
- `git checkout {{BRANCH}}` (refuse if dirty)
- `git rebase origin/{{BASE_BRANCH}}` — resolve conflicts only on
  the hunks introduced by the rebase
- For each conflicted file, prefer the additive merge when both sides
  are append-style (docs, manifests, exit-code lists); otherwise apply
  the operator-supplied rationale recorded in evidence
- Verification: `{{VERIFICATION_COMMANDS}}`
- Push: `git push --force-with-lease origin {{BRANCH}}`
- Audit evidence: `record_local_gate_evidence` from `lib/audit_log.sh`
  with the per-file resolution rationale

## Boundaries / interdictions

- Merge policy boundary: {{MERGE_POLICY}} — do NOT merge from this task.
- Out of scope: any change outside the rebase conflict hunks (no
  drive-by formatting, no scope expansion, no new features).
- No `--no-verify`, `--admin`, `git push --force` (use
  `--force-with-lease` only), branch-protection bypass.
- Refuse and report a blocker if `mergeable` is `UNKNOWN` at task
  start, or if any conflicted hunk requires a product decision the
  agent cannot make from the issue alone.

## Definition of Done verifiable

- [ ] `pwd` post-cd inside `{{AGENT_WORKDIR}}`
- [ ] `git status --short --branch` clean before any rebase
- [ ] No conflict markers (`<<<<<<< `, `=======`, `>>>>>>> `) remain
- [ ] No file outside the conflict hunks is modified
- [ ] No PR mutation outside `{{MUTATION_SCOPE}}`
- [ ] `git push --force-with-lease` succeeded; new HEAD reported in evidence

## Preuves attendues

- `pwd` post-cd
- `git config user.name && git config user.email`
- `git rev-parse HEAD` before and after the rebase
- List of resolved files with hunks count and rationale
- {{EXPECTED_EVIDENCE}}
- `gh pr view {{PR_NUMBER}} --repo {{REPO}} --json mergeable,mergeStateStatus`
  post-push (audit evidence)

— PR-ops dispatch generated by `scripts/dispatch_pr_ops.sh`. Mode: `{{MODE}}`. Wave: `{{WAVE_ID}}`.
