# Documentation Pack — ${DG_PROJECT_NAME}

- generated_at: `${DG_GENERATED_AT}`
- target_directory: `${DG_TARGET_DIR}`
- output_directory: `${DG_OUTPUT_DIR}`
- repo_metadata_signature: `${DG_REPO_METADATA_SIGNATURE}`
- gxp_grade_layer: `${DG_GXP_ENABLED}`
- six_sigma_layer: `${DG_SIXSIGMA_ENABLED}`

## Product Intent

${DG_PROJECT_INTENT}

## Layers Included

${DG_LAYERS_LIST}

## Pack Structure

| Section | Audience | Path |
| --- | --- | --- |
| Developer overview | engineers extending the project | `developer/overview.md` |
| Developer architecture | engineers extending the project | `developer/architecture.md` |
| Developer contribution | engineers extending the project | `developer/contribution.md` |
| User guide skeleton | end users of the project | `user/user-guide.md` |
| Operator runbook | operators running the project | `operator/operator-runbook.md` |
| Integration notes | integrators connecting to the project | `integration/integration-notes.md` |
| Validation evidence index | engineering and quality reviewers | `validation/evidence-index.md` |
| Maintenance and update policy | doc owners | `maintenance.md` |

GxP-grade and Six Sigma layers are appended only when explicitly requested.
Defaults remain neutral and do not infer regulated or measured operational
claims.

## Maintenance

The maintenance and update policy lives in `maintenance.md`. It defines who
owns each section, when each section must be revisited, and how the generator
records what was produced.

## Generator Inputs

This documentation pack was generated by the ORDO documentation generator
module. Inputs and the generation manifest are recorded in
`generated.manifest.json`. Operators can re-run the generator with updated
inputs to refresh the pack.
